version: '3.9'

services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex
    
  db:
    image: mongo:6.0.15
    container_name: mongo-poke-db
    restart: always
    environment:
      MONGODB_DATABASE: pokedex_dev
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017