services:
  db:
    image: postgres:17.4
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: teslo-shop-backend-db
    volumes:
      - ./data:/var/lib/postgresql/data
